version: '2'
services:

  server:
    build: .
    ports:
      - "6000:6000"
    networks:
      - ethereal-network

  mongodb:
    image: mongo
    ports:
      - "27017:27017"
    networks:
      - ethereal-network

  redis:
    image: redis
    ports:
     - "6379"
    networks:
      - ethereal-network

networks:
  ethereal-network:
    driver: bridge